import type { CsmsChargePoint } from './mapping';

/**
 * Sample network used when the CSMS cannot be reached (DEMO_DATA=true, the default
 * outside production). It uses the same raw shape as the real API so the mapping
 * and the UI are exercised identically.
 */
export const DEMO_CHARGE_POINTS: CsmsChargePoint[] = [
  {
    id: 'UB-SQUARE-01',
    name: 'Sukhbaatar Square',
    description: 'Underground parking level P1, bays 12–15.',
    address: 'Sukhbaatar Square 1, Chingeltei, Ulaanbaatar',
    latitude: 47.9186,
    longitude: 106.9177,
    tariffPerKwh: 550,
    chargePointVendor: 'ABB',
    chargePointModel: 'Terra 184',
    tags: ['ccs2', 'chademo', '120kw', 'c3:type2', 'c3:22kw', '24/7'],
    isOnline: true,
    lastSeenAt: new Date().toISOString(),
    connectors: [
      { connectorId: 0, status: 'Available' },
      { connectorId: 1, status: 'Available', availability: 'Operative' },
      { connectorId: 2, status: 'Charging', availability: 'Operative', currentTransactionId: 4821, lastPowerW: 92400, lastSocPercent: 63 },
      { connectorId: 3, status: 'Available', availability: 'Operative' },
    ],
  },
  {
    id: 'UB-SHANGRILA-01',
    name: 'Shangri-La Mall',
    description: 'Mall parking, level B2 near the north lift.',
    address: '19 Olympic Street, Sukhbaatar, Ulaanbaatar',
    latitude: 47.9128,
    longitude: 106.9143,
    tariffPerKwh: 620,
    chargePointVendor: 'Alpitronic',
    chargePointModel: 'HYC150',
    tags: ['ccs2', '150kw', 'mall', 'restaurant'],
    isOnline: true,
    lastSeenAt: new Date().toISOString(),
    connectors: [
      { connectorId: 0, status: 'Available' },
      { connectorId: 1, status: 'Charging', availability: 'Operative', currentTransactionId: 4822, lastPowerW: 141000, lastSocPercent: 41 },
      { connectorId: 2, status: 'Preparing', availability: 'Operative' },
    ],
  },
  {
    id: 'UB-BLUESKY-01',
    name: 'Blue Sky Tower',
    address: '17 Peace Avenue, Sukhbaatar, Ulaanbaatar',
    latitude: 47.9155,
    longitude: 106.9186,
    tariffPerKwh: 700,
    chargePointVendor: 'Kempower',
    chargePointModel: 'Satellite',
    tags: ['ccs2', 'type2', '180kw', 'hotel'],
    isOnline: true,
    connectors: [
      { connectorId: 0, status: 'Available' },
      { connectorId: 1, status: 'Available', availability: 'Operative' },
      { connectorId: 2, status: 'Faulted', availability: 'Operative', errorCode: 'ConnectorLockFailure' },
    ],
  },
  {
    id: 'UB-ZAISAN-01',
    name: 'Zaisan Hill Parking',
    address: 'Zaisan, Khan-Uul, Ulaanbaatar',
    latitude: 47.8825,
    longitude: 106.9218,
    tariffPerKwh: 500,
    chargePointVendor: 'Delta',
    chargePointModel: 'UFC 200',
    tags: ['ccs2', 'chademo', '200kw', 'outdoor'],
    isOnline: true,
    connectors: [
      { connectorId: 0, status: 'Available' },
      { connectorId: 1, status: 'Available', availability: 'Operative' },
      { connectorId: 2, status: 'Available', availability: 'Operative' },
    ],
  },
  {
    id: 'UB-STATEDEPT-01',
    name: 'State Department Store',
    address: '44 Peace Avenue, Chingeltei, Ulaanbaatar',
    latitude: 47.9179,
    longitude: 106.9052,
    tariffPerKwh: 580,
    chargePointVendor: 'Schneider',
    chargePointModel: 'EVlink Pro',
    tags: ['type2', '22kw', 'shopping'],
    isOnline: true,
    connectors: [
      { connectorId: 0, status: 'Available' },
      { connectorId: 1, status: 'Charging', availability: 'Operative', currentTransactionId: 4823, lastPowerW: 21600, lastSocPercent: 78 },
      { connectorId: 2, status: 'Charging', availability: 'Operative', currentTransactionId: 4824, lastPowerW: 20900, lastSocPercent: 55 },
    ],
  },
  {
    id: 'UB-NARANTUUL-01',
    name: 'Narantuul Market',
    address: 'Narantuul, Bayanzurkh, Ulaanbaatar',
    latitude: 47.9061,
    longitude: 106.9459,
    tariffPerKwh: 520,
    chargePointVendor: 'Sinexcel',
    chargePointModel: 'DC60',
    tags: ['gbt', 'ccs2', '60kw'],
    isOnline: false,
    lastSeenAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    connectors: [
      { connectorId: 0, status: 'Unavailable' },
      { connectorId: 1, status: 'Unavailable', availability: 'Operative' },
      { connectorId: 2, status: 'Unavailable', availability: 'Operative' },
    ],
  },
  {
    id: 'UB-HUNNU-01',
    name: 'Hunnu Mall',
    address: 'Buyant-Ukhaa, Khan-Uul, Ulaanbaatar',
    latitude: 47.8646,
    longitude: 106.7676,
    tariffPerKwh: 560,
    chargePointVendor: 'ABB',
    chargePointModel: 'Terra AC',
    tags: ['type2', '11kw', 'mall', 'wifi'],
    isOnline: true,
    connectors: [
      { connectorId: 0, status: 'Available' },
      { connectorId: 1, status: 'Available', availability: 'Operative' },
      { connectorId: 2, status: 'Available', availability: 'Operative' },
      { connectorId: 3, status: 'Unavailable', availability: 'Inoperative' },
    ],
  },
  {
    id: 'UB-AIRPORT-01',
    name: 'Chinggis Khaan Airport',
    description: 'Short-stay car park, row C.',
    address: 'Khushig Valley, Sergelen, Tuv',
    latitude: 47.6469,
    longitude: 106.8199,
    tariffPerKwh: 650,
    chargePointVendor: 'Alpitronic',
    chargePointModel: 'HYC300',
    tags: ['ccs2', 'chademo', '300kw', 'airport', '24/7'],
    isOnline: true,
    connectors: [
      { connectorId: 0, status: 'Available' },
      { connectorId: 1, status: 'Available', availability: 'Operative' },
      { connectorId: 2, status: 'Finishing', availability: 'Operative', currentTransactionId: 4825 },
    ],
  },
  {
    id: 'NALAIKH-01',
    name: 'Nalaikh Highway Stop',
    address: 'Nalaikh district, Ulaanbaatar',
    latitude: 47.7717,
    longitude: 107.2537,
    tariffPerKwh: 480,
    chargePointVendor: 'Star Charge',
    chargePointModel: 'Nova 90',
    tags: ['ccs2', 'gbt', '90kw', 'highway'],
    isOnline: true,
    connectors: [
      { connectorId: 0, status: 'Available' },
      { connectorId: 1, status: 'Available', availability: 'Operative' },
    ],
  },
  {
    id: 'DARKHAN-01',
    name: 'Darkhan City Centre',
    address: 'Darkhan-Uul, Darkhan',
    latitude: 49.4869,
    longitude: 105.9228,
    tariffPerKwh: 450,
    chargePointVendor: 'Sinexcel',
    chargePointModel: 'DC120',
    tags: ['ccs2', 'chademo', '120kw'],
    isOnline: true,
    connectors: [
      { connectorId: 0, status: 'Available' },
      { connectorId: 1, status: 'Available', availability: 'Operative' },
      { connectorId: 2, status: 'Available', availability: 'Operative' },
    ],
  },
];
